/** Figma-specified render sizes for event page icons (px). */
export const EVENT_ICON_SIZE = {
  meta: 16,
  chip: 14,
  buttonLeading: 12,
  buttonTrailing: 12,
  sessionTime: 12,
  sessionMaps: 16,
  sessionMore: 12,
  sessionBadge: 10,
  donationWallet: 24,
  donationWalletCircle: 40,
  donationItemFallback: 24,
  donationItemCircle: 40,
  bannerLabel: 12,
  dropdownItem: 16,
  tableVisibility: 16,
  statusBadge: 12,
  fieldHint: 14,
  coverPlaceholder: 32,
  overviewBadge: 10,
  tableMore: 16,
  search: 16,
  nav: 16,
  composeAction: 12,
} as const
